<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link rel="stylesheet" href="css/bulma.min.css">
        <title>Schnitzeljagd</title>
    </head>

    <body>
        <div class="container">
            <div class="box mt-5">
                <h1 class="title">Hennings Private Schnitzeljagd</h1>
                <h2 class="subtitle">Einfach damit er was zutun hat...</h2>

                <div class="content">
                    <p>
                        <div class="columns">
                            <div class="column is-three-quarters">
                                <p>
                                    Eine Schnitzeljagd war auf jeden Kindergeburtstag der Hammer und wenn wir ehrlich sind hat keiner von uns die Lust daran je verloren. Nun haben wir leider keine Ortskenntnis in Berlin und wohnen ja leider auch nicht um die Ecke. Aber ey, Tobi kann programmieren und ist gerade <i>"arbeitslos"</i>, also haben wir uns mal etwas Gedanken gemacht und diese digitale Schnitzeljagd für Dich erstellt. Auf deiner Jagd warten schwere und vielleicht auch ein paar nicht so schwere Rätsel auf Dich. Verzweifle nicht zu schnell! Für einige Rätsel brauchst Du vielleicht etwas Geduld und die Lösung kommt einem vielleicht erst nach 33 Minuten. Und wenn Du wirklich mal nicht weiterkommst, stehen wir Dir natürlich gerne mit einem kleinen Tipp zur Seite.
                                </p>
                                <p>
                                    Wir hoffen Du kannst Dir hier ein wenig die Zeit vertreiben und dass du Dich über die Rätsel freust die wir uns für Dich ausgedacht haben. 
                                </p>
                                <p>
                                    Viel Spaß wünschen Dir
                                </p> 
                                <i>Chrissey, Jules, Rieke, Torben, Tobi</i> und <i>Timo</i>

                                </p> 
                            </div>
                            <div class="column">
                                <figure>
                                    <img style="max-width: 50%" src="images/question.jpg">
                                </figure>
                            </div>
                        </div>
                    </p>

                    <p>
                        <ol>
                            <li>Die erste Zahl hast du bereits erhalten. - Done</li>
                            <li>binary encode -> ascii - Done</li>
                            <li>Quelltext gucken - Done</li>
                            <li>Schablone - Done</li>
                            <li>Irgendwas mit netflix szene, spotify, ..... - Done</li>
                            <li>Mitten Marktplatzrätsel, gegenüber von chrisseys bruder.... - Done</li>
                            <li>Zwischen Kinder u. Jugendfarm ev. (erster Hausbau) und du das letzte mal die Stollenschuhe geschnürrt hast und erstem Auto (Autohaus Brandt) und Riede - Done</li>
                            <li>telegram bot schreiben - cat api - Done</li>

                            <li>Programm eval</li>
                            <li>Leute nach Sachen fragen</li>
                            <li>optional: streichhölzer mit verschieben-witz</li>
                            <li>musik</i>
                        </ol> 
                    </p>

                    <p style="text-align: center"> 
                        <a class="button is-info" href="/1">Start</a> 
                    </p>

                    <div class="message is-primary">
                        <div class="message-header">
                            Bisherige Rätsel
                        </div>
                        <div class="message-body">
                           <ol>
                                ${d.puzzleList}
                           </ol>  
                        </div>
                    </div>
                                        
                </div>
            </div>
        </div>

    </body>
</html>